### ISSUE TITLE
Cannot type on macOS

### ISSUE THREAD

**Issue by Alex697279** [nab138/iloader#33]
I have a bug where whenever I go to type in my apple id in the spot for it, I simply cannot type. Ive tried restarting the phone, the computer, reinstalling the app, and even rolling back to older versions and nothing helps.

- OS MacOS 12.7.6
- iloader version: 1.1.4
- Package Format: .dmg (dragged into applications folder)

- Device: iPhone 14
- OS: iOS 26.1 Stable

**Comment by xxycho** [comment]
Same issue!

I'm on MacOS 12.7.6.
It seems related webkit CSS.

https://github.com/orgs/tauri-apps/discussions/3541
https://armno.in.th/blog/css-user-select/

**Comment by driley94** [comment]
also having the same issue on Mac 12.7.6

**Comment by nguyenvmai** [comment]
> Same issue!
> 
> I'm on MacOS 12.7.6. It seems related webkit CSS.
> 
> https://github.com/orgs/tauri-apps/discussions/3541 https://armno.in.th/blog/css-user-select/

I followed the second link's method and solved it (on my Mac at least). Specifically, right click to "Inspect Element", locate the line "-webkit-user-select: none;" untick/delete it and exit Inspect.

**Comment by nab138** [comment]
This should be fixed in v1.1.5

**Comment by driley94** [comment]
Unfortunately it is not fixed for me, I was able to sign in using "inspect element" and unchecking /* -webkit-user-select: none; */

**Comment by szzhouwh** [comment]
Unfortunately it is not fixed for me either.

**Comment by xxycho** [comment]
Try this.
Just right click and inspect element.

You can find Apple ID section and its CSS.
Uncheck /* -webkit-user-select: none;
And then you can type in ID field.

<img width="644" height="381" alt="Image" src="https://github.com/user-attachments/assets/40e4bdf8-89cf-40c1-a851-633cb4cc99ec" />

**Comment by hitmanex** [comment]
its not fixed. macos 12.7.6. editing the css works tho

**Comment by nab138** [comment]
Hopefully this should be resolved in 1.1.6. If not, please let me know

**Comment by nab138** [comment]
Closing due to inactivity. Feel free to re-open if the issue persists.
